Force-Safe-Enchantments: false
Experience-Cost-Modifiers:
    WOOD: 1.0
    STONE: 2.0
    GOLD: 0.5
    IRON: 1.4
    DIAMOND: 1.2
Initial-Level-Cost:
    WOOD: 3
    STONE: 5
    GOLD: 5
    IRON: 10
    DIAMOND: 20
Repair-Exp-Cost:
    WOOD: 0.8
    STONE: 1.0
    GOLD: 0.0
    IRON: 0.2
    DIAMOND: 0.15
Levable-Item-Types:
 - PICKAXE
 - AXE
 - SPADE
Cost-Increase: 1.25
Vanilla-Enchantments:
    ARROW_DAMAGE:
        Display-Name: Power
        Display-Material: ARROW
        Display-Durability: 0
        Display-Amount: 1
        Display-Lore: []
        Upgrade-Cost: 0
        Cost-Increase: 1.0
        Max-Level: 0
        Tools: []
    ARROW_FIRE:
        Display-Name: Flaming
        Display-Material: BLAZE_ROD
        Display-Durability: 0
        Display-Amount: 1
        Display-Lore: []
        Upgrade-Cost: 0
        Cost-Increase: 1.0
        Max-Level: 0
        Tools: []
    ARROW_INFINITE:
        Display-Name: Infinity
        Display-Material: ENDER_PEARL
        Display-Durability: 0
        Display-Amount: 1
        Display-Lore: []
        Upgrade-Cost: 0
        Cost-Increase: 1.0
        Max-Level: 0
        Tools: []
    ARROW_KNOCKBACK:
        Display-Name: Punch
        Display-Material: SULPHUR
        Display-Durability: 0
        Display-Amount: 1
        Display-Lore: []
        Upgrade-Cost: 0
        Cost-Increase: 1.0
        Max-Level: 0
        Tools: []
    DAMAGE_ALL:
        Display-Name: Sharpness
        Display-Material: DIAMOND_SWORD
        Display-Durability: 0
        Display-Amount: 1
        Display-Lore: []
        Upgrade-Cost: 0
        Cost-Increase: 1.0
        Max-Level: 0
        Tools: []
    DAMAGE_ARTHROPODS:
        Display-Name: Bane of Arthropods
        Display-Material: IRON_AXE
        Display-Durability: 0
        Display-Amount: 1
        Display-Lore: []
        Upgrade-Cost: 0
        Cost-Increase: 1.0
        Max-Level: 0
        Tools: []
    DAMAGE_UNDEAD:
        Display-Name: Smite
        Display-Material: GOLD_SWORD
        Display-Durability: 0
        Display-Amount: 1
        Display-Lore: []
        Upgrade-Cost: 0
        Cost-Increase: 1.0
        Max-Level: 0
        Tools: []
    DIG_SPEED:
        Display-Name: Efficiency
        Display-Material: DIAMOND_PICKAXE
        Display-Durability: 0
        Display-Amount: 1
        Display-Lore: []
        Upgrade-Cost: 500
        Cost-Increase: 1.5
        Max-Level: 5
        Tools:
         - PICKAXE
         - SPADE
         - AXE
    DURABILITY:
        Display-Name: Unbreaking
        Display-Material: IRON_INGOT
        Display-Durability: 0
        Display-Amount: 1
        Display-Lore: []
        Upgrade-Cost: 500
        Cost-Increase: 2
        Max-Level: 3
        Tools:
         - PICKAXE
         - SPADE
         - AXE
    FIRE_ASPECT:
        Display-Name: Fire Aspect
        Display-Material: BLAZE_POWDER
        Display-Durability: 0
        Display-Amount: 1
        Display-Lore: []
        Upgrade-Cost: 0
        Cost-Increase: 1.0
        Max-Level: 0
        Tools: []
    KNOCKBACK:
        Display-Name: Knockback
        Display-Material: SULPHUR
        Display-Durability: 0
        Display-Amount: 1
        Display-Lore: []
        Upgrade-Cost: 0
        Cost-Increase: 1.0
        Max-Level: 0
        Tools: []
    LOOT_BONUS_BLOCKS:
        Display-Name: Fortune
        Display-Material: GOLD_PICKAXE
        Display-Durability: 0
        Display-Amount: 1
        Display-Lore: []
        Upgrade-Cost: 500
        Cost-Increase: 2
        Max-Level: 3
        Tools:
         - PICKAXE
         - SPADE
         - AXE
    LOOT_BONUS_MOBS:
        Display-Name: Looting
        Display-Material: CHEST
        Display-Durability: 0
        Display-Amount: 1
        Display-Lore: []
        Upgrade-Cost: 0
        Cost-Increase: 1.0
        Max-Level: 0
        Tools: []
    LUCK:
        Display-Name: Luck of the Seas
        Display-Material: RAW_FISH
        Display-Durability: 0
        Display-Amount: 1
        Display-Lore: []
        Upgrade-Cost: 0
        Cost-Increase: 1.0
        Max-Level: 0
        Tools: []
    LURE:
        Display-Name: Lure
        Display-Material: FISHING_ROD
        Display-Durability: 0
        Display-Amount: 1
        Display-Lore: []
        Upgrade-Cost: 0
        Cost-Increase: 1.0
        Max-Level: 0
        Tools: []
    OXYGEN:
        Display-Name: Respiration
        Display-Material: BUCKET
        Display-Durability: 0
        Display-Amount: 1
        Display-Lore: []
        Upgrade-Cost: 0
        Cost-Increase: 1.0
        Max-Level: 0
        Tools: []
    PROTECTION_ENVIRONMENTAL:
        Display-Name: Protection
        Display-Material: IRON_CHESTPLATE
        Display-Durability: 0
        Display-Amount: 1
        Display-Lore: []
        Upgrade-Cost: 0
        Cost-Increase: 1.0
        Max-Level: 0
        Tools: []
    PROTECTION_EXPLOSIONS:
        Display-Name: Blast Protection
        Display-Material: DIAMOND_CHESTPLATE
        Display-Durability: 0
        Display-Amount: 1
        Display-Lore: []
        Upgrade-Cost: 0
        Cost-Increase: 1.0
        Max-Level: 0
        Tools: []
    PROTECTION_FALL:
        Display-Name: Feather Falling
        Display-Material: LEATHER_BOOTS
        Display-Durability: 0
        Display-Amount: 1
        Display-Lore: []
        Upgrade-Cost: 0
        Cost-Increase: 1.0
        Max-Level: 0
        Tools: []
    PROTECTION_FIRE:
        Display-Name: Fire Protection
        Display-Material: GOLD_CHESTPLATE
        Display-Durability: 0
        Display-Amount: 1
        Display-Lore: []
        Upgrade-Cost: 0
        Cost-Increase: 1.0
        Max-Level: 0
        Tools: []
    PROTECTION_PROJECTILE:
        Display-Name: Projectile Protection
        Display-Material: LEATHER_CHESTPLATE
        Display-Durability: 0
        Display-Amount: 1
        Display-Lore: []
        Upgrade-Cost: 0
        Cost-Increase: 1.0
        Max-Level: 0
        Tools: []
    SILK_TOUCH:
        Display-Name: Silk Touch
        Display-Material: SHEARS
        Display-Durability: 0
        Display-Amount: 1
        Display-Lore: []
        Upgrade-Cost: 5000
        Cost-Increase: 2
        Max-Level: 1
        Tools:
         - PICKAXE
         - SPADE
         - AXE
    THORNS:
        Display-Name: Thorns
        Display-Material: CACTUS
        Display-Durability: 0
        Display-Amount: 1
        Display-Lore: []
        Upgrade-Cost: 0
        Cost-Increase: 1.0
        Max-Level: 0
        Tools: []
    WATER_WORKER:
        Display-Name: Aqua Affinity
        Display-Material: SLIME_BALL
        Display-Durability: 0
        Display-Amount: 1
        Display-Lore: []
        Upgrade-Cost: 0
        Cost-Increase: 1.0
        Max-Level: 0
        Tools: []
Do-Check-Placed-Block: true
Exp-Awards:
    PICKAXE:
        STONE: 5
        NETHERRACK: 1
        GLOWSTONE: 50
        ENDER_STONE: 7 
        OBSIDIAN: 50
        COAL_ORE: 50
        IRON_ORE: 100
        GOLD_ORE: 150
        REDSTONE_ORE: 150
        LAPIS_ORE: 250
        EMERALD_ORE: 1000
        DIAMOND_ORE: 400
    SPADE:
        DIRT: 4
        MYCEL: 6
        GRASS: 5
        SAND: 4
        GRAVEL: 7
        SOUL_SAND: 8
    AXE:
        OAK_LOG: 5
        SPRUCE_LOG: 6
        BIRCH_LOG: 4
        JUNGLE_LOG: 6
        ACACIA_LOG: 7
        DARK_OAK_LOG: 6
    SWORD:
        CREEPER: 10
        SKELETON: 5 
        SPIDER: 10
        CAVE_SPIDER: 
        ZOMBIE: 5
        SLIME: 3
        GHAST: 50
        PIG_ZOMBIE: 
        ENDERMAN: 25
        SILVERFISH: 5
        BLAZE: 50
        MAGMA_CUBE: 3
        ENDER_DRAGON: 100
        PIG: 0
        SHEEP: 0 
        COW: 0
        CHICKEN: 0 
        SQUID: 0
        WOLF: 0
        MUSHROOM_COW: 0
        VILLAGER: 0 
    BOW:
        SPIDER: 0