Force-Safe-Enchantments: false
Experience-Cost-Modifiers:
    Tool:
        WOOD: 0.129
        STONE: 0.855
        GOLD: 0.049
        IRON: 1.55
        DIAMOND: 5.06
    Armor:
        LEATHER: 0.313
        CHAIN: 1.16
        GOLD: 0.254
        IRON: 1.55
        DIAMOND: 3.21
    Initial-Level-Cost:
    WOOD: 3
    STONE: 5
    GOLD: 3
    IRON: 10
    DIAMOND: 30
Repair-Exp-Cost:
    WOOD: 0.1
    STONE: 0.5
    GOLD: 0.0
    IRON: 0.3
    DIAMOND: 0.2
Levable-Item-Types:
 - PICKAXE
 - AXE
 - SPADE
Cost-Increase: 1.25
Do-Check-Placed-Block: true
Check-Duration-Seconds: 1814400
Exp-Awards:
    PICKAXE:
        STONE: 5
        SANDSTONE: 2
        NETHERRACK: 1
        GLOWSTONE: 20
        ENDER_STONE: 7 
        OBSIDIAN: 50
        COAL_ORE: 20
        IRON_ORE: 50
        GOLD_ORE: 60
        REDSTONE_ORE: 30
        LAPIS_ORE: 75
        EMERALD_ORE: 250
        DIAMOND_ORE: 100
    SPADE:
        DIRT: 5
        MYCEL: 8
        GRASS: 6
        SAND: 5
        GRAVEL: 7
        SOUL_SAND: 10
    AXE:
        OAK_LOG: 10
        SPRUCE_LOG: 14
        BIRCH_LOG: 8
        JUNGLE_LOG: 15
        ACACIA_LOG: 15
        DARK_OAK_LOG: 12
    SWORD:
        CREEPER: 10
        SKELETON: 5 
        SPIDER: 10
        CAVE_SPIDER: 
        ZOMBIE: 5
        SLIME: 3
        GHAST: 50
        PIG_ZOMBIE: 
        ENDERMAN: 25
        SILVERFISH: 5
        BLAZE: 50
        MAGMA_CUBE: 3
        ENDER_DRAGON: 100
        PIG: 0
        SHEEP: 0 
        COW: 0
        CHICKEN: 0 
        SQUID: 0
        WOLF: 0
        MUSHROOM_COW: 0
        VILLAGER: 0 
    BOW:
        SPIDER: 0
Experience-Formatting:
    '0': '&f'
    '100': '&e'
    '1000': '&a'
    '5000': '&9'
    '10000': '&d'
    '50000': '&c'